"use client";
// Danh sách các domain email ảo/thư rác phổ biến (được rút gọn để phù hợp)
const DISPOSABLE_EMAIL_DOMAINS = [
  // Các dịch vụ email tạm thời phổ biến
  '10minutemail.com', '10minutemail.co.uk', '10minutemail.net', '10minutemail.info',
  'temp-mail.org', 'temp-mail.io', 'temp-mail.com', 'tempmail.com', 'tempmail.org',
  'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.info', 'guerrillamail.biz',
  'mailinator.com', 'mailinator.net', 'mailinator.org', 'mailinator.xyz',
  'yopmail.com', 'yopmail.net', 'yopmail.org', 'yopmail.fr',
  'throwawaymail.com', 'throwawaymail.org', 'throwawaymail.io',
  'maildrop.cc', 'maildrop.gq', 'maildrop.cf', 'maildrop.ml',
  'getnada.com', 'getnada.xyz', 'getnada.net',
  'dispostable.com', 'dispostable.org', 'dispostable.net',
  'mailnesia.com', 'trashmail.com', 'trashmail.io', 'trashmail.net',
  'tempr.email', 'tempr.email.com', 'tempr.email.net',
  'tempmail.ninja', 'tempmail.plus', 'tempmail.net', 'tempmail.space',
  'tempmailgen.com', 'tempmailo.org', 'tempmail.pro', 'tempmailer.com',
  'tempmailer.org', 'tempmailer.de', 'tempmailer.net',
  'fakeinbox.com', 'fakeinbox.net', 'fakeinbox.org',
  'tempmailaddress.com', 'tempmailaddress.net',
  
  // Các dịch vụ email tạm thời khác
  '0wnd.net', '0wnd.org', '10mail.org', '20minutemail.com', '21cn.com',
  '2prong.com', '30minutemail.com', '3d-painting.com', '4warding.com',
  '5ymail.com', '6ip.us', '6paq.com', '6url.com', '75hosting.com',
  '7tags.com', '9ox.net', 'a-bc.net', 'afrobacon.com', 'ajaxapp.net',
  'amilegit.com', 'amiri.net', 'amiriindustries.com', 'anonymbox.com',
  'antichef.com', 'antichef.net', 'antispam.de', 'baxomale.ht.cx',
  'beefmilk.com', 'binkmail.com', 'bio-muesli.net', 'bobmail.info',
  'bodhi.lawlita.com', 'bofthew.com', 'bootybay.de', 'boun.cr',
  'bouncr.com', 'breakthru.com', 'brefmail.com', 'broadbandninja.com',
  'bsnow.net', 'bugmenot.com', 'bumpymail.com', 'casualdx.com',
  'centermail.com', 'centermail.net', 'chogmail.com', 'choicemail1.com',
  'cool.fr.nf', 'courriel.fr.nf', 'courrieltemporaire.com', 'cubiclink.com',
  'curryworld.de', 'cust.in', 'dacoolest.com', 'dandikmail.com',
  'deadaddress.com', 'despam.it', 'despammed.com', 'devnullmail.com',
  'dfgh.net', 'digitalsanctuary.com', 'dingbone.com', 'discardmail.com',
  'discardmail.de', 'disposable-email.ml', 'disposable.com', 'dodgeit.com',
  'dodgit.com', 'dodgit.org', 'dontreg.com', 'dontsendmespam.de',
  'drdrb.net', 'dump-email.info', 'dumpyemail.com', 'e4ward.com',
  'email60.com', 'emailias.com', 'emailmiser.com', 'emailsensei.com',
  'emailtemporanea.com', 'emailtemporanea.net', 'emailtemporario.com.br',
  'emailthe.net', 'emailtmp.com', 'emailwarden.com', 'emailx.at.hm',
  'emailxfer.com', 'emz.net', 'enterto.com', 'ephemail.net',
  'etranquil.com', 'etranquil.net', 'etranquil.org', 'explodemail.com',
  'fakeinformation.com', 'fastacura.com', 'fastchevy.com', 'fastchrysler.com',
  'fastkawasaki.com', 'fastmazda.com', 'fastmitsubishi.com', 'fastnissan.com',
  'fastsubaru.com', 'fastsuzuki.com', 'fasttoyota.com', 'fastyamaha.com',
  'filzmail.com', 'fizmail.com', 'frapmail.com', 'fudgerub.com',
  'garliclife.com', 'get1mail.com', 'get2mail.fr', 'getonemail.com',
  'getonemail.net', 'gishpuppy.com', 'gowikibooks.com', 'gowikicampus.com',
  'gowikicars.com', 'gowikifilms.com', 'gowikigames.com', 'gowikimusic.com',
  'gowikinetwork.com', 'gowikitravel.com', 'gowikitv.com', 'great-host.in',
  'greensloth.com', 'gsrv.co.uk', 'guerillamail.biz', 'guerillamail.com',
  'guerillamail.de', 'guerillamail.info', 'guerillamail.net', 'guerillamail.org',
  'guerrillamailblock.com', 'h.mintemail.com', 'h8s.org', 'hacccc.com',
  'haltospam.com', 'hatespam.org', 'hidemail.de', 'hidzz.com',
  'hmamail.com', 'hochsitze.com', 'hotpop.com', 'hulapla.de',
  'ieatspam.eu', 'ieatspam.info', 'ieh-mail.de', 'imails.info',
  'inboxclean.com', 'inboxclean.org', 'incognitomail.com', 'incognitomail.net',
  'incognitomail.org', 'ipoo.org', 'irish2me.com', 'iwi.net',
  'jetable.com', 'jetable.fr.nf', 'jetable.net', 'jetable.org',
  'jnxjn.com', 'junk1e.com', 'kasmail.com', 'kaspop.com',
  'klassmaster.com', 'klassmaster.net', 'klzlk.com', 'knol-power.nl',
  'kulturbetrieb.info', 'lhsdv.com', 'lifebyfood.com', 'link2mail.net',
  'litedrop.com', 'lol.ovpn.to', 'lookugly.com', 'lopl.co.cc',
  'lortemail.dk', 'lr78.com', 'm4ilweb.info', 'maboard.com',
  'mail-temporaire.fr', 'mail.by', 'mail.mezimages.net', 'mail.zzn.com',
  'mail1a.de', 'mail21.cc', 'mail2rss.org', 'mail333.com',
  'mail4trash.com', 'mailbidon.com', 'mailbiz.biz', 'mailblocks.com',
  'mailbucket.org', 'mailcatch.com', 'mailde.de', 'mailde.info',
  'maildx.com', 'maileater.com', 'mailexpire.com', 'mailfa.tk',
  'mailforspam.com', 'mailfreeonline.com', 'mailguard.me', 'mailin8r.com',
  'mailinater.com', 'mailinator2.com', 'mailincubator.com', 'mailismagic.com',
  'mailme.ir', 'mailme.lv', 'mailme24.com', 'mailmetrash.com',
  'mailmoat.info', 'mailms.com', 'mailnator.com', 'mailnull.com',
  'mailsac.com', 'mailscrap.com', 'mailshell.com', 'mailsiphon.com',
  'mailslite.com', 'mailtemp.info', 'mailtemp.net', 'mailtome.de',
  'mailtothis.com', 'mailtv.net', 'mailtv.tv', 'mailzilla.com',
  'mailzilla.org', 'mbx.cc', 'mega.zik.dj', 'meltmail.com',
  'messagebeamer.de', 'mezimages.net', 'mintemail.com', 'moburl.com',
  'moncourrier.fr.nf', 'monemail.fr.nf', 'monmail.fr.nf', 'monumentmail.com',
  'mt2009.com', 'mt2014.com', 'mx0.wwwnew.eu', 'mycleaninbox.net',
  'mypacks.net', 'mypartyclip.de', 'myphantomemail.com', 'myspaceinc.com',
  'myspaceinc.net', 'myspaceinc.org', 'myspacepimpedup.com', 'mytemp.email',
  'mytrashmail.com', 'neomailbox.com', 'nepwk.com', 'nervmich.net',
  'nervtmich.net', 'netmails.com', 'netmails.net', 'netzidiot.de',
  'neverbox.com', 'no-spam.ws', 'nobulk.com', 'noclickemail.com',
  'nogmailspam.info', 'nomail.xl.cx', 'nomail2me.com', 'nomorespamemails.com',
  'nospam.ze.tc', 'nospam4.us', 'nospamfor.us', 'nospamthanks.info',
  'notmailinator.com', 'nowhere.org', 'nowmymail.com', 'nurfuerspam.de',
  'nus.edu.sg', 'nwldx.com', 'objectmail.com', 'obobbo.com',
  'oneoffemail.com', 'onewaymail.com', 'online.ms', 'oopi.org',
  'ordinaryamerican.net', 'otherinbox.com', 'ourklips.com', 'outlawspam.com',
  'ovpn.to', 'owlpic.com', 'pancakemail.com', 'pcusers.otherinbox.com',
  'pepbot.com', 'pimpedupmyspace.com', 'pjjkp.com', 'politikerclub.de',
  'poofy.org', 'pookmail.com', 'privacy.net', 'proxymail.eu',
  'prtnx.com', 'punkass.com', 'putthisinyourspamdatabase.com', 'qq.com',
  'quickinbox.com', 'recode.me', 'recursor.net', 'regbypass.com',
  'regbypass.comsafe-mail.net', 'rejectmail.com', 'rhyta.com', 'rklips.com',
  'rmqkr.net', 'rppkn.com', 'rtrtr.com', 's0ny.net',
  'safe-mail.net', 'safersignup.de', 'safetymail.info', 'safetypost.de',
  'samsclass.info', 'sandelf.de', 'saynotospams.com', 'selfdestructingmail.com',
  'sendspamhere.com', 'sharklasers.com', 'shiftmail.com', 'shitmail.me',
  'shitware.nl', 'shmeriously.com', 'shortmail.net', 'sibmail.com',
  'sinnlos-mail.de', 'slaskpost.se', 'slopsbox.com', 'smellfear.com',
  'snakemail.com', 'sneakemail.com', 'sofort-mail.de', 'sogetthis.com',
  'soodonims.com', 'spam.la', 'spam.su', 'spam4.me', 'spamail.de',
  'spamarrest.com', 'spambob.net', 'spambob.org', 'spambog.com',
  'spambog.de', 'spambog.net', 'spambog.ru', 'spambox.info',
  'spambox.irishspringrealty.com', 'spambox.us', 'spamcannon.com', 'spamcannon.net',
  'spamcero.com', 'spamcon.org', 'spamcorptastic.com', 'spamcowboy.com',
  'spamcowboy.net', 'spamcowboy.org', 'spamday.com', 'spamex.com',
  'spamfree24.com', 'spamfree24.de', 'spamfree24.eu', 'spamfree24.info',
  'spamfree24.net', 'spamfree24.org', 'spamgourmet.com', 'spamherelots.com',
  'spamhereplease.com', 'spamhole.com', 'spamify.com', 'spaminator.de',
  'spamkill.info', 'spaml.com', 'spaml.de', 'spammotel.com',
  'spamobox.com', 'spamsalad.in', 'spamslicer.com', 'spamspot.com',
  'spamthis.co.uk', 'spamthisplease.com', 'spamtrail.com', 'speed.1s.fr',
  'spikio.com', 'spoofmail.de', 'stuffmail.de', 'supergreatmail.com',
  'supermailer.jp', 'suremail.info', 'talkinator.com', 'teewars.org',
  'teleworm.com', 'teleworm.us', 'temp-mail.org', 'temp-mail.ru',
  'temp.emeraldwebmail.com', 'temp.headstrong.de', 'tempail.com', 'tempalias.com',
  'tempe-mail.com', 'tempemail.biz', 'tempemail.com', 'tempemail.co.za',
  'tempemail.net', 'tempinbox.co.uk', 'tempinbox.com', 'tempmail2.com',
  'tempmaildemo.com', 'tempomail.fr', 'temporarily.de', 'temporarioemail.com.br',
  'temporaryemail.net', 'temporaryemail.us', 'temporaryforwarding.com', 'temporaryinbox.com',
  'temporarymailaddress.com', 'tempsky.com', 'tempthe.net', 'tempymail.com',
  'thankyou2010.com', 'thc.st', 'thelimestones.com', 'thisisnotmyrealemail.com',
  'thismail.net', 'thrma.com', 'tmail.com', 'tmailinator.com',
  'tmailservices.com', 'tradermail.info', 'trash-amil.com', 'trash-mail.at',
  'trash-mail.cf', 'trash-mail.com', 'trash-mail.de', 'trash-mail.ga',
  'trash-mail.gq', 'trash-mail.ml', 'trash-mail.tk', 'trash2009.com',
  'trashdevil.com', 'trashdevil.de', 'trashmail.at', 'trashmail.com',
  'trashmail.de', 'trashmail.me', 'trashmail.net', 'trashmail.org',
  'trashmail.ws', 'trashmailer.com', 'trashymail.com', 'trashymail.net',
  'trbvm.com', 'trialbytrivia.com', 'trillianpro.com', 'turual.com',
  'twinmail.de', 'tyldd.com', 'uggsrock.com', 'upliftnow.com',
  'uplipht.com', 'venompen.com', 'veryrealemail.com', 'viditag.com',
  'vip.188.com', 'vip.163.com', 'vip.sina.com', 'vip.sohu.com',
  'vip.tom.com', 'vipmail.in', 'vipmail.pw', 'vipmail.ru',
  'vipmail365.com', 'vixletdev.com', 'vubby.com', 'wasteland.rfc822.org',
  'webemail.me', 'weg-werf-email.de', 'wegwerf-emails.de', 'wegwerfadresse.de',
  'wegwerfemail.com', 'wegwerfemail.de', 'wegwerfmail.de', 'wegwerfmail.info',
  'wegwerfmail.net', 'wegwerfmail.org', 'wetrainbayarea.com', 'wetrainbayarea.org',
  'wh4f.org', 'whyspam.me', 'willselfdestruct.com', 'winemaven.info',
  'wronghead.com', 'wuzup.net', 'wuzupmail.net', 'www.e4ward.com',
  'www.gishpuppy.com', 'www.mailinator.com', 'wwwnew.eu', 'xagloo.com',
  'xemaps.com', 'xing886.uu.gl', 'xmail.com', 'xoxy.net',
  'yep.it', 'yogamaven.com', 'yopmail.gq', 'yuurok.com',
  'z1p.biz', 'za.com', 'zehnminutenmail.de', 'zippymail.info',
  'zoemail.net', 'zomg.info'
];

// Kiểm tra xem email có phải là email ảo không
export const isDisposableEmail = (email: string): boolean => {
  if (!email || !email.includes('@')) return false;
  
  const domain = email.split('@')[1].toLowerCase();
  
  // Kiểm tra domain trong danh sách đen
  if (DISPOSABLE_EMAIL_DOMAINS.includes(domain)) {
    return true;
  }
  
  // Kiểm tra các mẫu email tạm thời
  const tempEmailPatterns = [
    // Các mẫu thông thường
    /^temp[\d.-]*\./i,
    /^tmp[\d.-]*\./i,
    /^fake[\d.-]*\./i,
    /^test[\d.-]*\./i,
    /^dummy[\d.-]*\./i,
    /^spam[\d.-]*\./i,
    /^trash[\d.-]*\./i,
    /^junk[\d.-]*\./i,
    /^throw[\d.-]*\./i,
    /^disposable[\d.-]*\./i,
    /^temporary[\d.-]*\./i,
    
    // Các mẫu đuôi miền
    /\.local$/i,
    /\.localdomain$/i,
    /\.test$/i,
    /\.example$/i,
    /\.invalid$/i,
    /\.local$/i,
    /\.localhost$/i,
    /\.test$/i,
    
    // Các dịch vụ email tạm thời phổ biến
    /^mailinator\./i,
    /^yopmail\./i,
    /^tempmail\./i,
    /^trashmail\./i,
    /^guerrillamail\./i,
    /^dispostable\./i,
    /^10minutemail\./i,
    /^throwawaymail\./i,
    /^tempr\.email/i,
    /^tempmailer\./i,
    /^tempmailaddress\./i,
    
    // Các mẫu khác
    /^no[-.]?reply\./i,
    /^noreply\./i,
    /^noreply[\d.-]*\./i,
    /^no[-.]?response\./i,
    /^dev[-.]?null\./i,
    /^blackhole\./i,
    /^devnull\./i,
    /^null\./i,
    /^void\./i,
    /^discard\./i,
    /^sink\./i,
    /^bitbucket\./i,
    /^mohmal\./i,
    /^sharklasers\./i,
    /^guerrillamail\./i,
    /^guerrillamailblock\./i,
    /^spam4\.me/i,
    /^spambog\./i,
    /^spamgourmet\./i,
    /^spamherelots\./i,
    /^spamhereplease\./i,
    /^spamhole\./i,
    /^spamify\./i,
    /^spaminator\./i,
    /^spamkill\./i,
    /^spaml\./i,
    /^spammotel\./i,
    /^spamobox\./i,
    /^spamsalad\./i,
    /^spamslicer\./i,
    /^spamspot\./i,
    /^spamthis\./i,
    /^spamtrail\./i,
    /^spam\.la/i,
    /^spam\.su/i,
    /^spam4\.me/i,
    /^spamail\./i,
    /^spamarrest\./i,
    /^spambob\./i,
    /^spamcero\./i,
    /^spamcon\./i,
    /^spamcorptastic\./i,
    /^spamcowboy\./i,
    /^spamday\./i,
    /^spamex\./i,
    /^spamfree24\./i,
    /^tempmail\./i,
    /^temp-mail\./i,
    /^tempmailer\./i,
    /^tempmailaddress\./i,
    /^tempmailgen\./i,
    /^tempmailo\./i,
    /^tempomail\./i,
    /^temporarily\./i,
    /^temporary\./i,
    /^temporaryemail\./i,
    /^temporaryforwarding\./i,
    /^temporaryinbox\./i,
    /^temporarymailaddress\./i,
    /^tempsky\./i,
    /^tempthe\./i,
    /^tempymail\./i,
    /^trash-mail\./i,
    /^trash2009\./i,
    /^trashdevil\./i,
    /^trashmail\./i,
    /^trashmailer\./i,
    /^trashymail\./i,
    /^trashymail\./i,
    /^trbvm\./i,
    /^trialbytrivia\./i,
    /^trillianpro\./i,
    /^turual\./i,
    /^twinmail\./i,
    /^tyldd\./i,
    /^uggsrock\./i,
    /^upliftnow\./i,
    /^uplipht\./i,
    /^venompen\./i,
    /^veryrealemail\./i,
    /^viditag\./i,
    /^vip\./i,
    /^vixletdev\./i,
    /^vubby\./i,
    /^wasteland\./i,
    /^webemail\./i,
    /^weg-werf-email\./i,
    /^wegwerf-email/i,
    /^wegwerfadresse\./i,
    /^wegwerfemail\./i,
    /^wegwerfmail\./i,
    /^wetrainbayarea\./i,
    /^wh4f\./i,
    /^whyspam\./i,
    /^willselfdestruct\./i,
    /^winemaven\./i,
    /^wronghead\./i,
    /^wuzup\./i,
    /^xagloo\./i,
    /^xemaps\./i,
    /^xing886\./i,
    /^xmail\./i,
    /^xoxy\./i,
    /^yep\.it/i,
    /^yogamaven\./i,
    /^yuurok\./i,
    /^z1p\./i,
    /^za\.com/i,
    /^zehnminutenmail\./i,
    /^zippymail\./i,
    /^zoemail\./i,
    /^zomg\./i,
    
    // Các mẫu IP
    /^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/,
    /^\[\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\]$/,
    
    // Các mẫu tên miền lạ
    /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\./i,
    /^[a-f0-9]{32}\./i,
    /^[a-f0-9]+\./i,
    
    // Các mẫu tên miền phổ biến khác
    /^example\./i,
    /^domain\./i,
    /^mydomain\./i,
    /^somedomain\./i,
    /^yourdomain\./i,
    /^testdomain\./i,
    /^localdomain\./i,
    /^local\./i,
    
    // Các mẫu tên miền dành riêng theo RFC 2606
    /\.example\.(com|net|org)$/i,
    /\.test$/i,
    /\.invalid$/i,
    /\.localhost$/i,
    
    // Các mẫu tên miền đặc biệt
    /\.onion$/i,
    /\.i2p$/i,
    /\.bit$/i,
    /\.bazar$/i,
    
    // Các mẫu tên miền nội bộ
    /\.intranet$/i,
    /\.internal$/i,
    /\.private$/i,
    /\.localnet$/i,
    
    // Các mẫu tên miền thử nghiệm
    /\.test$/i,
    /\.example$/i,
    /\.invalid$/i,
    /\.local$/i,
    /\.localhost$/i,
    
    // Các mẫu tên miền dành riêng
    /\.arpa$/i,
    /\.home$/i,
    /\.lan$/i,
    
    // Các mẫu tên miền đặc biệt khác
    /\.nohost$/i,
    /\.nohost\./i,
    /^mail\./i,
    /^smtp\./i,
    /^pop\./i,
    /^imap\./i,
    /^mail[0-9]*\./i,
    /^smtp[0-9]*\./i,
    /^pop[0-9]*\./i,
    /^imap[0-9]*\./i,
    
    // Các mẫu tên miền khác
    /^autocontactor\./i,
    /^autocontact\./i,
    /^automailer\./i,
    /^autoreply\./i,
    /^autosender\./i,
    /^bounce\./i,
    /^bounced\./i,
    /^bouncer\./i,
    /^bounces\./i,
    /^bounceback\./i,
    /^bouncehandler\./i,
    /^bouncer\./i,
    /^bounce\./i,
    /^bounced\./i,
    /^bounces\./i,
    /^bounceback\./i,
    /^bouncehandler\./i,
    /^bouncer\./i,
    /^bounce\./i,
    /^bounced\./i,
    /^bounces\./i,
    /^bounceback\./i,
    /^bouncehandler\./i
  ];
  
  // Kiểm tra tất cả các mẫu
  const isTempEmail = tempEmailPatterns.some(pattern => pattern.test(domain));
  
  // Kiểm tra thêm một số điều kiện đặc biệt
  const hasMultipleDots = (domain.match(/\./g) || []).length > 2; // Nhiều hơn 2 dấu chấm
  const hasConsecutiveDots = /\.\./.test(domain); // Có 2 dấu chấm liên tiếp
  const hasInvalidChars = /[^a-z0-9.-]/.test(domain); // Có ký tự không hợp lệ
  const startsOrEndsWithDot = /^\.|\.$/.test(domain); // Bắt đầu hoặc kết thúc bằng dấu chấm
  const hasConsecutiveDashes = /--/.test(domain); // Có 2 dấu gạch ngang liên tiếp
  
  return isTempEmail || hasMultipleDots || hasConsecutiveDots || hasInvalidChars || startsOrEndsWithDot || hasConsecutiveDashes;
};

// Kiểm tra định dạng email hợp lệ
export const isValidEmail = (email: string): boolean => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

// Kiểm tra mật khẩu mạnh
export const isStrongPassword = (password: string): boolean => {
  // Ít nhất 8 ký tự, 1 chữ hoa, 1 chữ thường, 1 số, 1 ký tự đặc biệt
  const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>/?]).{8,}$/;
  return passwordRegex.test(password);
};
